---

- name: Create Calibre directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ calibre_config_directory }}"
    - "{{ calibre_books_directory }}"

- name: Set Docker container parameters
  set_fact:
    calibre_container_parameters:
      name: "{{ calibre_name }}"
      image: "{{ calibre_image }}"
      state: started
      published_ports: "{{ calibre_ports }}"
      volumes:
        - "{{ calibre_config_directory }}:/config"
        - "{{ calibre_books_directory }}:/books"
      env: "{{ calibre_environment_variables }}"

- name: Create Calibre container
  docker_container: "{{ calibre_container_parameters | combine(calibre_docker_additional_options) }}"
  register: calibre_container
